INSERT INTO USER(USERNAME, PASSWORD, ROLE) VALUES ('admin', 'admin', 'admin');
INSERT INTO USER(USERNAME, PASSWORD, ROLE) VALUES ('user1', 'user1', 'user');
INSERT INTO USER(USERNAME, PASSWORD, ROLE) VALUES ('user2', 'user2', 'user');
